
'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

interface LanguageContextType {
  language: 'en' | 'es';
  setLanguage: (lang: 'en' | 'es') => void;
  t: (key: string) => string;
  isHydrated: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Hero Section
    'hero.title': 'Smart Energy, Real Savings.',
    'hero.subtitle': 'Clarity and control over your energy.',
    'hero.cta.primary': 'Get Your Quote',
    'hero.cta.secondary': 'See Services',

    // Home - The Challenge
    'home.challengeTitle': 'Energy Management is Complex. We Make it Profitable.',
    'home.challengeSubtitle': 'Rising costs, opaque regulations, and inefficient consumption are eating into your margins. Teravolta provides the clarity and strategy you need.',
    'home.challengeItem1': 'Unpredictable Energy Costs',
    'home.challengeItem2': 'Regulatory Compliance Risks',
    'home.challengeItem3': 'Hidden Inefficiencies',

    // Home - Solutions (Outcome Based)
    'home.solutionsTitle': 'Comprehensive Energy Solutions',
    'home.solution1Title': 'Strategic Consulting',
    'home.solution1Desc': 'Secure optimal PPA rates and terms.',
    'home.solution2Title': 'Energy Efficiency for Homes and Businesses',
    'home.solution2Desc': 'Real-time data to cut waste.',
    'home.solution3Title': 'Service Quality',
    'home.solution3Desc': 'Expert defense against disputes.',

    // Home - Featured Case Study
    'home.featuredCaseStudyTitle': 'Impact in Action',
    'home.featuredCaseStudySubtitle': 'See how we saved a major manufacturer $2.1M.',
    'home.caseStudyStat': '$2.1M Savings',
    'home.caseStudyContext': 'Manufacturing Plant • PPA Restructuring',

    // Header
    'header.home': 'Home',
    'header.services': 'Services',
    'header.projects': 'Projects',
    'header.about': 'About',
    'header.contact': 'Contact',
    'header.account': 'Account',
    'header.getQuote': 'Get Quote',

    // Projects Page
    'projects.title': 'Impact in Action',
    'projects.subtitle': 'Real results from real clients. See how we help companies across Central America optimize consumption and reduce costs.',
    'projects.casesTitle': 'Featured Success Stories',
    'projects.casesSubtitle': 'Explore our portfolio of delivered solutions, from industrial solar installations to complex regulatory advocacy.',
    'projects.problem': 'Challenge',
    'projects.solution': 'Solution',
    'projects.result': 'Results',
    'projects.efficiency': 'Energy Efficiency',
    'projects.consulting': 'Energy Consulting',
    'projects.advocacy': 'Energy Advocacy',
    'projects.project1.client': 'Industrial Plant',
    'projects.project1.problem': 'High energy costs and need for sustainable sourcing without capital expenditure.',
    'projects.project1.solution': 'Evaluation and selection of a Photovoltaic Provider under a PPA model.',
    'projects.project1.result': 'Project awarded to a top-tier developer with significant long-term savings.',
    'projects.project1.tag1': 'PPA Selection',
    'projects.project1.tag2': 'Industrial',
    'projects.project1.tag3': 'Renewables',
    'projects.project2.client': 'Educational Institution',
    'projects.project2.problem': 'Needed to reduce carbon footprint and costs but had budget constraints for investment.',
    'projects.project2.solution': 'Structured a Leasing model for photovoltaic installation, requiring zero upfront capital.',
    'projects.project2.result': 'Immediate savings on electricity bill and successful implementation of green energy.',
    'projects.project2.tag1': 'Leasing',
    'projects.project2.tag2': 'Education',
    'projects.project2.tag3': 'No CapEx',
    'projects.project3.client': 'Multi-site Organization',
    'projects.project3.problem': 'Complex energy needs across multiple locations requiring a unified business strategy.',
    'projects.project3.solution': 'Developed an Energy as a Service (EaaS) Business Plan including regulatory and financial modeling.',
    'projects.project3.result': 'Robust plan accepted for capital acquisition and strategic deployment.',
    'projects.project3.tag1': 'EaaS',
    'projects.project3.tag2': 'Business Plan',
    'projects.project3.tag3': 'Multi-site',
    'projects.project4.client': 'Renewable Generator',
    'projects.project4.problem': 'Discrepancies in transmission charge calculations affecting profitability.',
    'projects.project4.solution': 'Detailed verification of methodology and technical report for the regulatory authority.',
    'projects.project4.result': 'Successful claim submission with technical backing to adjust charges.',
    'projects.project4.tag1': 'Regulatory',
    'projects.project4.tag2': 'Transmission',
    'projects.project4.tag3': 'Generation',
    'projects.project5.client': 'Social Club',
    'projects.project5.problem': 'Evaluating a photovoltaic proposal with complex financial variables.',
    'projects.project5.solution': 'Financial analysis utilizing Monte Carlo simulation to validate assumptions and risks.',
    'projects.project5.result': 'Clear financial indicators provided confidence for project approval.',
    'projects.project5.tag1': 'Financial Analysis',
    'projects.project5.tag2': 'PV Proposal',
    'projects.project5.tag3': 'Risk Assessment',
    'projects.project6.client': 'Residential Client',
    'projects.project6.problem': 'Frequent power outages affecting quality of life and security.',
    'projects.project6.solution': 'Energy audit and sizing of a battery backup system tailored to consumption patterns.',
    'projects.project6.result': 'Auto-sufficiency during outages and optimized energy security.',
    'projects.project6.tag1': 'Residential',
    'projects.project6.tag2': 'Backup Power',
    'projects.project6.tag3': 'Audit',
    'projects.project7.client': 'Telecom Operator',
    'projects.project7.problem': 'Large consumer transitioning to the wholesale electricity market.',
    'projects.project7.solution': 'Evaluation of electricity supply offers, comparing costs, risks, and contractual terms.',
    'projects.project7.result': 'Selected the most competitive supplier with optimized long-term rates.',
    'projects.project7.tag1': 'Wholesale Market',
    'projects.project7.tag2': 'Supply Contract',
    'projects.project7.tag3': 'Telecom',
    'projects.impactTitle': 'Our Combined Impact',
    'projects.impactSubtitle': 'Measurable results across all our client projects demonstrate the power of data-driven energy solutions.',
    'projects.totalSavings': 'Total Client Savings',
    'projects.avgReduction': 'Average Cost Reduction',
    'projects.co2Reduction': 'Tons CO₂ Reduced',
    'projects.satisfaction': 'Client Satisfaction',
    'projects.industriesTitle': 'Industries We Serve',
    'projects.industriesSubtitle': 'Our expertise spans across multiple sectors, each with unique energy challenges and requirements.',
    'projects.manufacturing': 'Manufacturing',
    'projects.hospitality': 'Hospitality',
    'projects.healthcare': 'Healthcare',
    'projects.banking': 'Banking',
    'projects.logistics': 'Logistics',
    'projects.retail': 'Retail',
    'projects.testimonialsTitle': 'What Our Clients Say',
    'projects.testimonialsSubtitle': 'Real feedback from real clients who have experienced the TeraVolta difference.',
    'projects.testimonial1.text': 'TeraVolta transformed our energy management completely. The real-time data and insights allowed us to make informed decisions that saved us over $200,000 in the first year alone.',
    'projects.testimonial1.name': 'Carlos Mendoza',
    'projects.testimonial1.position': 'Operations Director, TechManufacturing Corp',
    'projects.testimonial2.text': 'The level of expertise and attention to detail was exceptional. They didn’t just install equipment - they created a comprehensive energy strategy that continues to deliver results.',
    'projects.testimonial2.name': 'Maria Rodriguez',
    'projects.testimonial2.position': 'Facility Manager, Plaza Business Center',
    'projects.testimonial3.text': 'For a medical facility, reliability is everything. TeraVolta delivered a solution that not only reduced our costs but also enhanced our operational security and compliance.',
    'projects.testimonial3.name': 'Dr. Roberto Silva',
    'projects.testimonial3.position': 'Administrator, Regional Medical Center',
    'projects.ctaTitle': 'Ready to Join Our Success Stories?',
    'projects.ctaSubtitle': 'Let us help you achieve similar results with a customized energy solution designed specifically for your business.',
    'projects.startProject': 'Start Your Project',
    'projects.seeServices': 'See Our Services',
    'projects.scrollIndicator': 'Scroll to explore',

    // About Page
    'about.title': 'About TeraVolta',
    'about.heroDescription': 'Transforming energy management in Central America through data-driven solutions and cutting-edge technology.',
    'about.ourStoryTitle': 'Our Story',
    'about.ourStoryText1': 'TeraVolta was founded in Panama with the mission to revolutionize how businesses understand and manage their energy consumption. We were born from the recognition that the traditional energy industry operates with too many assumptions and too little concrete data.',
    'about.ourStoryText2': 'Our approach is based on precise data analysis, advanced IoT technology, and personalized solutions that deliver measurable and transparent results for each client.',
    'about.dataGapTitle': 'The Data Gap Challenge',
    'about.dataGapText': 'We identified that over 80% of companies in Central America make energy decisions without sufficient data. TeraVolta closes this gap with real-time monitoring and predictive analytics.',
    'about.impactTitle': 'Our Impact in Numbers',
    'about.impactDescription': 'Real results that demonstrate the power of data-driven energy solutions.',
    'about.clientsServed': 'Clients Served',
    'about.totalSavings': 'Total Savings',
    'about.avgReduction': 'Average Reduction',
    'about.co2Reduction': 'Tons CO₂ Avoided',
    'about.ourValues': 'Our Core Values',
    'about.integrityTitle': 'Integrity',
    'about.integrityText': 'We operate with absolute transparency, providing accurate data and honest recommendations that prioritize our clients’ best interests above all else.',
    'about.innovationTitle': 'Innovation',
    'about.innovationText': 'We embrace emerging technologies and cutting-edge methodologies to stay ahead of the energy sector evolution and deliver superior solutions.',
    'about.collaborationTitle': 'Collaboration',
    'about.collaborationText': 'We believe in the power of working together. We build strong relationships with clients, partners, and communities to create a more sustainable energy future.',
    'about.foundersTitle': 'Meet Our Founders',
    'about.foundersDescription': 'A unique combination of technological experience, energy industry knowledge, and innovation in data science',
    'about.agustinTitle': 'Co-Founder & Director of Technology',
    'about.agustinBio': 'Agustín is a STEM entrepreneur with academic training from Florida State University. He combines a solid technical foundation in computer science with a strategic focus on innovation and sustainability. With experience in developing AI-driven solutions and data analysis systems, he specializes in bridging the gap between advanced technology and process optimization in the energy sector.',
    'about.agustinEducation': 'B.S. in STEM Entrepreneurship, Florida State University (Minors in Innovation & CS)',
    'about.agustinExperience': 'Experience: AI-driven solutions, chatbots, and data systems prototyping.',
    'about.agustinSpecialty': 'Expertise: Technology strategy, energy analytics, and digital optimization.',
    'about.roqueTitle': 'Chief Energy Officer',
    'about.roqueBio': 'Energy industry veteran with over 20 years in power generation, distribution, and regulation. Former ASEP commissioner and energy consultant. Roque brings unparalleled deep knowledge and regulatory experience.',
    'about.roqueEducation': 'MS Electrical Engineering, Universidad Tecnológica de Panamá',
    'about.roqueExperience': 'Previous: ASEP Commissioner, AES Panama',
    'about.roqueSpecialty': 'Specialty: Electrical Systems, Regulation, Market Analysis',
    'about.alexTitle': 'Chief Data Officer',
    'about.alexBio': 'Data science innovator with expertise in machine learning and energy analytics. PhD in Applied Mathematics with focus on time series analysis and predictive modeling for energy systems.',
    'about.alexEducation': 'PhD Applied Mathematics, MIT',
    'about.alexExperience': 'Previous: Tesla Energy, McKinsey Analytics',
    'about.alexSpecialty': 'Specialty: ML, Predictive Analytics, Energy Modeling',

    // Terms of Service
    'terms.title': 'Terms of Service',
    'terms.lastUpdated': 'Last Updated: December 2025',
    'terms.intro': 'Welcome to TeraVolta. By accessing or using our services, you agree to be bound by these Terms of Service.',
    'terms.section1.title': '1. Description of Services',
    'terms.section1.content': 'TeraVolta provides energy consulting, efficiency monitoring, and regulatory advocacy services. Our platform helps users understand and optimize their energy consumption.',
    'terms.section2.title': '2. User Responsibilities',
    'terms.section2.content': 'You are responsible for maintaining the confidentiality of your account and for all activities that occur under your account. You agree to provide accurate and complete information.',
    'terms.section3.title': '3. Limitation of Liability',
    'terms.section3.content': 'While we strive for accuracy, energy savings and results may vary based on external factors. TeraVolta is not liable for fluctuations in market prices or individual usage patterns.',
    'terms.section4.title': '4. Intellectual Property',
    'terms.section4.content': 'All content, logos, and technology on this site are the property of TeraVolta and are protected by international copyright laws.',

    // Privacy Policy
    'privacy.title': 'Privacy Policy',
    'privacy.lastUpdated': 'Last Updated: December 2025',
    'privacy.intro': 'At TeraVolta, your privacy is our priority. This policy explains how we collect, use, and protect your personal and energy data.',
    'privacy.section1.title': '1. Data We Collect',
    'privacy.section1.content': 'We collect information you provide (name, email) and energy usage data (utility bills, smart meter data) to provide our services.',
    'privacy.section2.title': '2. How We Use Data',
    'privacy.section2.content': 'Your data is used to generate energy analysis, identify savings opportunities, and improve our services. We do not sell your personal data to third parties.',
    'privacy.section3.title': '3. Data Security',
    'privacy.section3.content': 'We implement industry-standard security measures to protect your information from unauthorized access, alteration, or disclosure.',
    'privacy.section4.title': '4. Your Rights',
    'privacy.section4.content': 'You have the right to access, update, or request the deletion of your personal information at any time through your account settings.',
    'about.ctaTitle': 'Ready to Transform Your Energy Management?',
    'about.ctaDescription': 'Join hundreds of satisfied clients who have already optimized their energy consumption with our data-driven solutions.',
    'about.getQuote': 'Get Quote',
    'about.contactUs': 'Contact Us',

    // Footer
    'footer.description': 'Transforming energy management in Central America through innovative solutions and advanced data analytics.',
    'footer.services': 'Services',
    'footer.company': 'Company',
    'footer.contactInfo': 'Contact Information',
    'footer.rights': '© 2025 TeraVolta. All rights reserved.',
    'footer.terms': 'Terms of Service',
    'footer.privacy': 'Privacy Policy',
    'footer.address': 'Panama City, Panama',
    'footer.efficiency': 'Energy Efficiency',
    'footer.consulting': 'Energy Consulting',
    'footer.advocacy': 'Energy Advocacy',
    'footer.about': 'About Us',
    'footer.projects': 'Projects',
    'footer.contact': 'Contact',

    // Home Page
    'home.heroTitle': 'Smart Energy, Real Savings.',
    'home.heroSubtitle': 'Clarity and control over your energy.',
    'home.seeServices': 'See Services',
    'home.servicesTitle': 'Our Services',
    'home.servicesSubtitle': 'Comprehensive consulting, efficiency, and advocacy solutions tailored to your needs',
    'home.service1.title': 'Strategic Consulting',
    'home.service1.description': 'We drive strategic decisions in PPA structuring, Contract Evaluation, and sustainable business development that optimize costs and competitiveness.',
    'home.service1.bullets': 'Requirement definition, Request for proposals, Proposal evaluation, Provider selection, Asset Due Diligence, Business plan design, Public Tenders Offer',
    'home.service2.title': 'Energy Efficiency for Homes and Businesses',
    'home.service2.description': 'We analyze the load profile of your home, business, or industry to identify energy efficiency solutions.',
    'home.service2.bullets': 'Understand your electric bill, Monitoring Energy Use, Analysis of Energy Consumption, Identification of Savings, Opportunities with renewable energies',
    'home.service3.title': 'Service Quality',
    'home.service3.description': 'We advise on claims for electricity service quality to distributors in Panama and before the Regulatory Body (ASEP).',
    'home.service3.bullets': 'Quality claims, Regulatory advice, ASEP representation',
    'home.learnMore': 'Learn More',
    'home.expertiseTitle': 'Our Expertise',
    'home.expertiseSubtitle': 'Deep knowledge across technology, markets, and implementation',
    'home.dataAiTitle': 'Data Science & AI',
    'home.dataAiDescription': 'Advanced analytics and machine learning to transform your energy data into actionable insights.',
    'home.panamaMarketTitle': 'Panama Market & Regulation',
    'home.panamaMarketDescription': 'Deep understanding of local energy markets, regulations, and opportunities in Panama.',
    'home.technologyTitle': 'Technology & Implementation',
    'home.technologyDescription': 'Seamless integration and deployment of energy management solutions tailored to your infrastructure.',
    'home.whyUsTitle': 'Data, Not Estimates',
    'home.whyUsDescription1': 'Unlike traditional energy consultants who rely on estimates and assumptions, we use your actual meter data to identify real savings opportunities.',
    'home.ctaTitle': 'Ready for Control?',
    'home.ctaDescription': 'Take the first step towards energy clarity and start saving today.',
    'home.getYourQuote': 'Get Your Quote',
    'home.clientsServed': 'Clients Served',
    'home.totalSavings': 'Total Savings',
    'home.avgReduction': 'Avg Reduction',
    'home.efficiencyAchieved': 'Efficiency Achieved',
    'home.completeSupport': 'Complete Support',
    'home.supportDescription': 'Service and assistance from start to finish',
    'home.scrollIndicator': 'Swipe to see more',

    // Quote Results Page
    'quote.results.title': 'Your Personalized Analysis',
    'quote.results.hello': 'Hello',
    'quote.results.company': 'Company',
    'quote.results.property': 'sq ft property • Type',
    'quote.results.analysisComplete': 'Analysis Complete',
    'quote.results.preliminaryNotice': 'Preliminary Analysis',
    'quote.results.preliminaryText': 'These results are estimates based on general information. For a complete and personalized analysis, we will need to conduct a detailed evaluation at your property.',
    'quote.results.billAnalysis': 'Bill Analysis',
    'quote.results.currentConsumption': 'Current Consumption',
    'quote.results.monthlyAverage': 'Monthly Average',
    'quote.results.annualTotal': 'Annual Total',
    'quote.results.peakDemand': 'Peak Demand',
    'quote.results.avgDailyConsumption': 'Average Daily Consumption',
    'quote.results.efficiencyRating': 'Efficiency Rating',
    'quote.results.belowAverage': 'Below Average',
    'quote.results.consumesMore': 'Your property consumes more energy than necessary',
    'quote.results.wasteFactors': 'Main Waste Factors',
    'quote.results.wasteFactor1': 'Peak hours consumption',
    'quote.results.wasteFactor2': 'Old equipment',
    'quote.results.wasteFactor3': 'Lack of intelligent management',
    'quote.results.wasteFactor4': 'Non-optimized lighting',
    'quote.results.peakHoursAnalysis': 'Peak Hours Analysis',
    'quote.results.morning': 'Morning',
    'quote.results.afternoon': 'Afternoon',
    'quote.results.evening': 'Evening',
    'quote.results.opportunity': 'Opportunity',
    'quote.results.opportunityText': 'Optimizing usage during these hours can significantly reduce your costs',
    'quote.results.savingsPotential': 'Savings Potential',
    'quote.results.preliminaryProjections': 'Projections based on preliminary analysis',
    'quote.results.monthlySavings': 'Monthly Savings',
    'quote.results.reduction': 'reduction',
    'quote.results.annualSavings': 'Annual Savings',
    'quote.results.basedOnOptimization': 'Based on complete optimization',
    'quote.results.fiveYearProjection': '5-Year Projection',
    'quote.results.totalEstimatedSavings': 'Total estimated savings',
    'quote.results.quoteSummary': 'Quote Summary',
    'quote.results.serviceDetails': 'Service Details',
    'quote.results.selectedService': 'Selected Service',
    'quote.results.energyEfficiency': 'Energy Efficiency',
    'quote.results.propertyType': 'Property Type',
    'quote.results.area': 'Area',
    'quote.results.sqFeet': 'sq feet',
    'quote.results.measurementDevice': 'Measurement Device',
    'quote.results.purchase': 'Purchase',
    'quote.results.rental': 'Rental',
    'quote.results.connectivity': 'Connectivity',
    'quote.results.estimatedInvestment': 'Estimated Investment',
    'quote.results.analysisOptimization': 'Analysis and Optimization',
    'quote.results.wifiConnectivity': 'Wi-Fi Connectivity',
    'quote.results.connectivity3g': '3G Connectivity',
    'quote.results.included': 'Included',
    'quote.results.initialTotal': 'Initial Total',
    'quote.results.additionalMonthlyCost': 'Additional monthly cost',
    'quote.results.roi': 'Return on Investment',
    'quote.results.roiText': 'With estimated savings of ${savings}/month, the investment would be recovered in approximately {months} months',
    'quote.results.whatNext': 'What’s Next?',
    'quote.results.preliminaryText2': 'This is a preliminary analysis based on general information. For a complete and accurate evaluation, we need to conduct a detailed analysis at your property.',
    'quote.results.twoOptions': 'You have two options to continue:',
    'quote.results.haveQuestions': 'Have Questions?',
    'quote.results.talkToExperts': 'Talk to our experts to clarify doubts and get more information about your analysis.',
    'quote.results.contactExpert': 'Contact Expert',
    'quote.results.startNow': 'Start Now',
    'quote.results.proceedPayment': 'Proceed with payment to start your detailed analysis and energy optimization.',
    'quote.results.proceedToPayment': 'Proceed to Payment',
    'quote.results.guarantee': '100% satisfaction guarantee or your money back',
    'quote.results.loadingAnalysis': 'Loading analysis...',
    'quote.results.estimationNote': 'Estimates are based on general data and may vary according to detailed analysis.',
    'quote.results.preliminaryAnalysisNote': 'This is a preliminary analysis based on general information.',
    'quote.results.projectionsNote': 'Projection based on preliminary analysis. Actual results may vary.',

    // Contract Flow
    'contract.title': 'Contract Energy Efficiency Service',
    'contract.step1': 'Payment Information',
    'contract.step2': 'Successful Payment',
    'contract.step3': 'Schedule Installation',
    'contract.step4': 'Final Confirmation',
    'contract.loading': 'Loading...',
    'contract.changeService': '← Change Service',
    'contract.selectedService': 'Selected service: Energy Efficiency',
    'contract.serviceDescription': 'Enter your card details to proceed with the service payment.',
    'contract.summaryTitle': 'Service Summary',
    'contract.summaryFeature1': 'Complete efficiency analysis',
    'contract.summaryFeature2': 'Smart meter installation',
    'contract.summaryFeature3': 'Real-time monitoring',
    'contract.summaryFeature4': 'Monthly savings reports',
    'contract.totalToPay': 'Total to Pay',
    'contract.includesInstallation': 'Includes installation and setup',
    'contract.cardholderName': 'Cardholder name',
    'contract.cardholderPlaceholder': 'Name as it appears on card',
    'contract.cardNumber': 'Card number',
    'contract.cardNumberPlaceholder': '0000 0000 0000 0000',
    'contract.acceptCards': 'We accept:',
    'contract.visaMastercard': 'Visa and Mastercard',
    'contract.expiryDate': 'Expiry date',
    'contract.expiryPlaceholder': 'MM/YY',
    'contract.securityCode': 'Security code',
    'contract.securityPlaceholder': 'CVV',
    'contract.securePayment': 'Secure Payment',
    'contract.securePaymentText': 'Your information is protected with 256-bit SSL encryption. We do not store card data.',
    'contract.completeFields': 'Please complete all fields',
    'contract.cardholderRequired': 'Cardholder name is required',
    'contract.invalidCard': 'Invalid card number',
    'contract.invalidExpiry': 'Invalid expiry date',
    'contract.invalidCvv': 'Invalid CVV',
    'contract.processingPayment': 'Processing payment...',
    'contract.payAmount': 'Pay $2,500',
    'contract.paymentSuccessful': 'Payment Successful!',
    'contract.paymentProcessed': 'Your payment has been processed successfully. Now let’s schedule the installation.',
    'contract.purchaseDetails': 'Purchase Details',
    'contract.service': 'Service',
    'contract.completeEnergyEfficiency': 'Complete Energy Efficiency',
    'contract.paymentMethod': 'Payment method',
    'contract.cardEnding': 'Card ending in',
    'contract.totalPaid': 'Total Paid',
    'contract.nextStep': 'Next Step',
    'contract.nextStepText': 'Now we need to schedule the installation of your smart meter. Select the date and time that works best for you.',
    'contract.scheduleInstallation': 'Schedule Installation',
    'contract.scheduleTitle': 'Schedule Installation',
    'contract.scheduleDescription': 'Select the date and time that works best for you for the installation.',
    'contract.selectDate': 'Select a date',
    'contract.availableSlots': 'Available slots for',
    'contract.available': 'Available',
    'contract.appointmentSummary': 'Appointment Summary',
    'contract.estimatedDuration': 'Estimated duration: 2-3 hours',
    'contract.previous': 'Previous',
    'contract.confirmingAppointment': 'Confirming appointment...',
    'contract.confirmAppointment': 'Confirm Appointment',
    'contract.allReady': 'All Ready!',
    'contract.serviceContracted': 'Your service has been successfully contracted. We will contact you soon to confirm the details.',
    'contract.yourInstallationAppointment': 'Your Installation Appointment',
    'contract.at': 'at',
    'contract.nextSteps': 'Next Steps',
    'contract.nextStep1': 'You will receive a confirmation email with all details',
    'contract.nextStep2': 'We will call you 24 hours before to confirm the appointment',
    'contract.nextStep3': 'A certified technician will perform the installation',
    'contract.nextStep4': 'You will have immediate access to your monitoring dashboard',
    'contract.finalSummary': 'Final Summary',
    'contract.backToHome': 'Back to Home',
    'contract.myAccount': 'My Account',
    'contract.changeAppointment': 'Need to change your appointment? Call us at (507) 6000-0000',
    'contract.days.DOM': 'SUN',
    'contract.days.LUN': 'MON',
    'contract.days.MAR': 'TUE',
    'contract.days.MIE': 'WED',
    'contract.days.JUE': 'THU',
    'contract.days.VIE': 'FRI',
    'contract.days.SAB': 'SAT',
    'contract.months.Ene': 'Jan',
    'contract.months.Feb': 'Feb',
    'contract.months.Mar': 'Mar',
    'contract.months.Abr': 'Apr',
    'contract.months.May': 'May',
    'contract.months.Jun': 'Jun',
    'contract.months.Jul': 'Jul',
    'contract.months.Ago': 'Aug',
    'contract.months.Sep': 'Sep',
    'contract.months.Oct': 'Oct',
    'contract.months.Nov': 'Nov',
    'contract.months.Dic': 'Dec',

    // Property Types
    'property.residential': 'Residential',
    'property.apartment': 'Apartment',
    'property.smallBusiness': 'Small Business',
    'property.office': 'Office',
    'property.industrial': 'Industrial',

    // Inquiry Confirmation Page
    'inquiry.confirmation.title': 'Request Submitted!',
    'inquiry.confirmation.subtitle': 'Thank you for your inquiry. Our team will contact you very soon.',
    'inquiry.confirmation.whatNext': 'What\'s next?',
    'inquiry.confirmation.within24hours': 'Within 24 hours',
    'inquiry.confirmation.within24hoursText': 'You will receive an email confirmation and an expert will review your request.',
    'inquiry.confirmation.initialConsultation': 'Initial consultation',
    'inquiry.confirmation.initialConsultationText': 'We will schedule a call to better understand your specific needs.',
    'inquiry.confirmation.customProposal': 'Custom proposal',
    'inquiry.confirmation.customProposalText': 'We will send you a detailed proposal adapted to your specific project.',
    'inquiry.confirmation.needHelp': 'Need help?',
    'inquiry.confirmation.phone': '+507 6000-0000',
    'inquiry.confirmation.email': 'info@teravolta.com',
    'inquiry.confirmation.schedule': 'Monday to Friday 8:00 AM - 6:00 PM',
    'inquiry.confirmation.backToHome': 'Back to Home',
    'inquiry.confirmation.viewServices': 'View Services',
  },
  es: {
    // Hero Section
    'hero.title': 'Energía Inteligente, Ahorros Reales.',
    'hero.subtitle': 'Claridad y control sobre tu energía.',
    'hero.cta.primary': 'Obtener Cotización',
    'hero.cta.secondary': 'Ver Servicios',

    // Home - The Challenge
    'home.challengeTitle': 'La Gestión Energética es Compleja. Nosotros la Hacemos Rentable.',
    'home.challengeSubtitle': 'Costos crecientes, regulaciones opacas y consumo ineficiente afectan tus márgenes. TeraVolta te da la claridad y estrategia que necesitas.',
    'home.challengeItem1': 'Costos Energéticos Impredecibles',
    'home.challengeItem2': 'Riesgos de Cumplimiento Regulatorio',
    'home.challengeItem3': 'Ineficiencias Ocultas',

    // Home - Solutions (Outcome Based)
    'home.solutionsTitle': 'Soluciones Energéticas Integrales',
    'home.solution1Title': 'Consultoría Estratégica',
    'home.solution1Desc': 'Asegura las mejores tarifas y términos PPA.',
    'home.solution2Title': 'Eficiencia Energética para Hogares y Negocios',
    'home.solution2Desc': 'Datos en tiempo real para eliminar desperdicios.',
    'home.solution3Title': 'Calidad de Servicio',
    'home.solution3Desc': 'Defensa experta ante disputas y reclamos.',

    // Home - Featured Case Study
    'home.featuredCaseStudyTitle': 'Impacto en Acción',
    'home.featuredCaseStudySubtitle': 'Mira cómo ahorramos $2.1M a una gran manufacturera.',
    'home.caseStudyStat': '$2.1M Ahorro',
    'home.caseStudyContext': 'Planta Industrial • Reestructuración PPA',

    // Header
    'header.home': 'Inicio',
    'header.services': 'Servicios',
    'header.projects': 'Proyectos',
    'header.about': 'Nosotros',
    'header.contact': 'Contacto',
    'header.account': 'Cuenta',
    'header.getQuote': 'Obtener Cotización',

    // Projects Page
    'projects.title': 'Nuestras Historias de Éxito',
    'projects.subtitle': 'Resultados reales de clientes reales. Descubre cómo hemos ayudado a empresas en toda Centroamérica a optimizar su consumo energético y reducir costos.',
    'projects.casesTitle': 'Casos de Estudio Destacados',
    'projects.casesSubtitle': 'Cada proyecto representa un desafío único y una solución personalizada que entregó resultados medibles.',
    'projects.problem': 'Desafío',
    'projects.solution': 'Solución',
    'projects.result': 'Resultados',
    'projects.efficiency': 'Eficiencia Energética',
    'projects.consulting': 'Consultoría Energética',
    'projects.advocacy': 'Defensa Energética',
    'projects.project1.client': 'Planta Industrial',
    'projects.project1.problem': 'Altos costos energéticos y necesidad de suministro sostenible sin inversión de capital.',
    'projects.project1.solution': 'Evaluación y selección de Proveedor Fotovoltaico bajo modelo PPA.',
    'projects.project1.result': 'Proyecto adjudicado a desarrollador de primer nivel con ahorros significativos a largo plazo.',
    'projects.project1.tag1': 'Selección PPA',
    'projects.project1.tag2': 'Industrial',
    'projects.project1.tag3': 'Renovables',
    'projects.project2.client': 'Institución Educativa',
    'projects.project2.problem': 'Necesidad de reducir huella de carbono y costos pero con limitaciones presupuestarias para inversión.',
    'projects.project2.solution': 'Estructuración de modelo Leasing para instalación fotovoltaica, requiriendo cero capital inicial.',
    'projects.project2.result': 'Ahorros inmediatos en factura eléctrica e implementación exitosa de energía verde.',
    'projects.project2.tag1': 'Leasing',
    'projects.project2.tag2': 'Educación',
    'projects.project2.tag3': 'Sin CapEx',
    'projects.project3.client': 'Organización Multisede',
    'projects.project3.problem': 'Necesidades energéticas complejas en múltiples ubicaciones requiriendo una estrategia comercial unificada.',
    'projects.project3.solution': 'Desarrollo de Plan de Negocios de Energía como Servicio (EaaS) incluyendo modelado regulatorio y financiero.',
    'projects.project3.result': 'Plan robusto aceptado para adquisición de capital y despliegue estratégico.',
    'projects.project3.tag1': 'EaaS',
    'projects.project3.tag2': 'Plan de Negocios',
    'projects.project3.tag3': 'Multisede',
    'projects.project4.client': 'Generador Renovable',
    'projects.project4.problem': 'Discrepancias en cálculos de cargos de transmisión afectando la rentabilidad.',
    'projects.project4.solution': 'Verificación detallada de metodología y reporte técnico para la autoridad regulatoria.',
    'projects.project4.result': 'Presentación exitosa de reclamo con respaldo técnico para ajustar cargos.',
    'projects.project4.tag1': 'Regulatorio',
    'projects.project4.tag2': 'Transmisión',
    'projects.project4.tag3': 'Generación',
    'projects.project5.client': 'Club Social',
    'projects.project5.problem': 'Evaluación de propuesta fotovoltaica con variables financieras complejas.',
    'projects.project5.solution': 'Análisis financiero utilizando simulación de Monte Carlo para validar supuestos y riesgos.',
    'projects.project5.result': 'Indicadores financieros claros proporcionaron confianza para aprobación del proyecto.',
    'projects.project5.tag1': 'Análisis Financiero',
    'projects.project5.tag2': 'Propuesta FV',
    'projects.project5.tag3': 'Riesgos',
    'projects.project6.client': 'Cliente Residencial',
    'projects.project6.problem': 'Frecuentes cortes de energía afectando calidad de vida y seguridad.',
    'projects.project6.solution': 'Auditoría energética y dimensionamiento de sistema de respaldo a baterías adaptado a patrones de consumo.',
    'projects.project6.result': 'Autosuficiencia durante cortes y seguridad energética optimizada.',
    'projects.project6.tag1': 'Residencial',
    'projects.project6.tag2': 'Respaldo',
    'projects.project6.tag3': 'Auditoría',
    'projects.project7.client': 'Operador de Telecomunicaciones',
    'projects.project7.problem': 'Gran consumidor transicionando al mercado mayorista de electricidad.',
    'projects.project7.solution': 'Evaluación de ofertas de suministro eléctrico, comparando costos, riesgos y términos contractuales.',
    'projects.project7.result': 'Selección del proveedor más competitivo con tarifas optimizadas a largo plazo.',
    'projects.project7.tag1': 'Mercado Mayorista',
    'projects.project7.tag2': 'Contrato Suministro',
    'projects.project7.tag3': 'Telecom',
    'projects.impactTitle': 'Nuestro Impacto Combinado',
    'projects.impactSubtitle': 'Resultados medibles en todos nuestros proyectos demuestran el poder de las soluciones energéticas basadas en datos.',
    'projects.totalSavings': 'Ahorros Totales de Clientes',
    'projects.avgReduction': 'Reducción Promedio de Costos',
    'projects.co2Reduction': 'Toneladas CO₂ Reducidas',
    'projects.satisfaction': 'Satisfacción del Cliente',
    'projects.industriesTitle': 'Industrias que Servimos',
    'projects.industriesSubtitle': 'Nuestra experiencia abarca múltiples sectores, cada uno con desafíos y requisitos energéticos únicos.',
    'projects.manufacturing': 'Manufactura',
    'projects.hospitality': 'Hotelería',
    'projects.healthcare': 'Salud',
    'projects.banking': 'Bancario',
    'projects.logistics': 'Logística',
    'projects.retail': 'Retail',
    'projects.testimonialsTitle': 'Lo que Dicen Nuestros Clientes',
    'projects.testimonialsSubtitle': 'Testimonios reales de clientes reales que han experimentado la diferencia TeraVolta.',
    'projects.testimonial1.text': 'TeraVolta transformó completamente nuestra gestión energética. Los datos en tiempo real y las perspectivas nos permitieron tomar decisiones informadas que nos ahorraron más de $200,000 solo en el primer año.',
    'projects.testimonial1.name': 'Carlos Mendoza',
    'projects.testimonial1.position': 'Director de Operaciones, TechManufacturing Corp',
    'projects.testimonial2.text': 'El nivel de experiencia y atención al detalle fue excepcional. No solo instalaron equipos - crearon una estrategia energética integral que continúa entregando resultados.',
    'projects.testimonial2.name': 'María Rodríguez',
    'projects.testimonial2.position': 'Gerente de Instalaciones, Plaza Business Center',
    'projects.testimonial3.text': 'Para una instalación médica, la confiabilidad lo es todo. TeraVolta entregó una solución que no solo redujo nuestros costos sino que también mejoró nuestra seguridad operativa y cumplimiento.',
    'projects.testimonial3.name': 'Dr. Roberto Silva',
    'projects.testimonial3.position': 'Administrador, Centro Médico Regional',
    'projects.ctaTitle': '¿Listo para Unirte a Nuestras Historias de Éxito?',
    'projects.ctaSubtitle': 'Permítenos ayudarte a lograr resultados similares con una solución energética personalizada diseñada específicamente para tu negocio.',
    'projects.startProject': 'Iniciar tu Proyecto',
    'projects.seeServices': 'Ver Nuestros Servicios',
    'projects.scrollIndicator': 'Desliza para explorar',

    // About Page
    'about.title': 'Sobre TeraVolta',
    'about.heroDescription': 'Transformando la gestión energética en Centroamérica a través de soluciones basadas en datos y tecnología de vanguardia.',
    'about.ourStoryTitle': 'Nuestra Historia',
    'about.ourStoryText1': 'TeraVolta fue fundada en Panamá con la misión de revolucionar cómo las empresas entienden y gestionan su consumo energético. Nacimos del reconocimiento de que la industria energética tradicional opera con demasiadas suposiciones y muy pocos datos concretos.',
    'about.ourStoryText2': 'Nuestro enfoque se basa en análisis de datos precisos, tecnología IoT avanzada y soluciones personalizadas que entregan resultados medibles y transparentes para cada cliente.',
    'about.dataGapTitle': 'El Desafío de la Brecha de Datos',
    'about.dataGapText': 'Identificamos que más del 80% de las empresas en Centroamérica toman decisiones energéticas sin datos suficientes. TeraVolta cierra esta brecha con monitoreo en tiempo real y análisis predictivo.',
    'about.impactTitle': 'Nuestro Impacto en Números',
    'about.impactDescription': 'Resultados reales que demuestran el poder de las soluciones energéticas basadas en datos.',
    'about.clientsServed': 'Clientes Atendidos',
    'about.totalSavings': 'Ahorros Generados',
    'about.avgReduction': 'Reducción Promedio',
    'about.co2Reduction': 'Toneladas CO₂ Evitadas',
    'about.ourValues': 'Nuestros Valores Fundamentales',
    'about.integrityTitle': 'Integridad',
    'about.integrityText': 'Operamos con transparencia absoluta, proporcionando datos precisos y recomendaciones honestas que priorizan los mejores intereses de nuestros clientes por encima de todo.',
    'about.innovationTitle': 'Innovación',
    'about.innovationText': 'Adoptamos tecnologías emergentes y metodologías de vanguardia para mantenernos a la cabeza de la evolución del sector energético y ofrecer soluciones superiores.',
    'about.collaborationTitle': 'Colaboración',
    'about.collaborationText': 'Creemos en el poder de trabajar juntos. Construimos relaciones sólidas con clientes, socios y comunidades para crear un futuro energético más sostenible.',
    'about.foundersTitle': 'Conoce a Nuestros Fundadores',
    'about.foundersDescription': 'Una combinación única de experiencia tecnológica, conocimiento de la industria energética e innovación en ciencia de datos',
    'about.agustinTitle': 'Co-Fundador y Director de Tecnología',
    'about.agustinBio': 'Emprendedor en STEM graduado de Florida State University, Agustín fusiona una sólida formación técnica en ciencias de la computación con una visión estratégica en innovación energética. Se especializa en el desarrollo de soluciones de inteligencia artificial y sistemas de análisis de datos aplicados a la sostenibilidad, con amplia experiencia en la creación de herramientas de soporte para la toma de decisiones y la optimización de procesos operativos reales.',
    'about.agustinEducation': 'B.S. en Emprendimiento STEM, Florida State University (Minors en Innovación y CS)',
    'about.agustinExperience': 'Experiencia: Soluciones IA, chatbots y prototipado de sistemas de datos.',
    'about.agustinSpecialty': 'Especialidad: Consultoría Estratégica, Eficiencia Energética, Calidad de Servicio',

    // Terms of Service
    'terms.title': 'Términos de Servicio',
    'terms.lastUpdated': 'Última actualización: Diciembre 2025',
    'terms.intro': 'Bienvenido a TeraVolta. Al acceder o utilizar nuestros servicios, usted acepta estar sujeto a estos Términos de Servicio.',
    'terms.section1.title': '1. Descripción de los Servicios',
    'terms.section1.content': 'TeraVolta ofrece consultoría energética, monitoreo de eficiencia y servicios de defensa regulatoria. Nuestra plataforma ayuda a los usuarios a comprender y optimizar su consumo de energía.',
    'terms.section2.title': '2. Responsabilidades del Usuario',
    'terms.section2.content': 'Usted es responsable de mantener la confidencialidad de su cuenta y de todas las actividades que ocurran bajo ella. Acepta proporcionar información precisa y completa.',
    'terms.section3.title': '3. Limitación de Responsabilidad',
    'terms.section3.content': 'Si bien nos esforzamos por lograr la precisión, los ahorros de energía y los resultados pueden variar según factores externos. TeraVolta no es responsable de las fluctuaciones en los precios del mercado o los patrones de uso individuales.',
    'terms.section4.title': '4. Propiedad Intelectual',
    'terms.section4.content': 'Todo el contenido, logotipos y tecnología de este sitio son propiedad de TeraVolta y están protegidos por las leyes internacionales de derechos de autor.',

    // Privacy Policy
    'privacy.title': 'Política de Privacidad',
    'privacy.lastUpdated': 'Última actualización: Diciembre 2025',
    'privacy.intro': 'En TeraVolta, su privacidad es nuestra prioridad. Esta política explica cómo recopilamos, utilizamos y protegemos sus datos personales y energéticos.',
    'privacy.section1.title': '1. Datos que Recopilamos',
    'privacy.section1.content': 'Recopilamos la información que usted proporciona (nombre, correo electrónico) y datos de uso de energía (facturas de servicios públicos, datos de medidores inteligentes) para brindar nuestros servicios.',
    'privacy.section2.title': '2. Cómo Utilizamos los Datos',
    'privacy.section2.content': 'Sus datos se utilizan para generar análisis de energía, identificar oportunidades de ahorro y mejorar nuestros servicios. No vendemos sus datos personales a terceros.',
    'privacy.section3.title': '3. Seguridad de los Datos',
    'privacy.section3.content': 'Implementamos medidas de seguridad estándar de la industria para proteger su información contra el acceso, alteración o divulgación no autorizados.',
    'privacy.section4.title': '4. Sus Derechos',
    'privacy.section4.content': 'Usted tiene derecho a acceder, actualizar o solicitar la eliminación de su información personal en cualquier momento a través de la configuración de su cuenta.',
    'about.roqueTitle': 'Director de Energía',
    'about.roqueBio': 'Veterano de la industria energética con más de 20 años en generación, distribución y regulación de energía. Ex-comisionado de ASEP y consultor energético. Roque aporta conocimiento profundo sin igual y experiencia regulatoria.',
    'about.roqueEducation': 'MS Ingeniería Eléctrica, Universidad Tecnológica de Panamá',
    'about.roqueExperience': 'Anterior: Comisionado ASEP, AES Panamá',
    'about.roqueSpecialty': 'Especialidad: Sistemas Eléctricos, Regulación, Análisis de Mercado',
    'about.alexTitle': 'Director de Datos',
    'about.alexBio': 'Innovador en ciencia de datos con experiencia en aprendizaje automático y análisis energético. PhD en Matemáticas Aplicadas con enfoque en análisis de series temporales y modelado predictivo para sistemas energéticos.',
    'about.alexEducation': 'PhD Matemáticas Aplicadas, MIT',
    'about.alexExperience': 'Anterior: Tesla Energy, McKinsey Analytics',
    'about.alexSpecialty': 'Especialidad: ML, Análisis Predictivo, Modelado Energético',
    'about.ctaTitle': '¿Listo para Transformar tu Gestión Energética?',
    'about.ctaDescription': 'Únete a cientos de clientes satisfechos que ya han optimizado su consumo energético con nuestras soluciones basadas en datos.',
    'about.getQuote': 'Obtener Cotización',
    'about.contactUs': 'Contáctanos',

    // Footer
    'footer.description': 'Transformando la gestión energética en Centroamérica a través de soluciones innovadoras y análisis de datos avanzados.',
    'footer.services': 'Servicios',
    'footer.company': 'Empresa',
    'footer.contactInfo': 'Información de Contacto',
    'footer.rights': '© 2025 TeraVolta. Todos los derechos reservados.',
    'footer.terms': 'Términos de Servicio',
    'footer.privacy': 'Política de Privacidad',
    'footer.address': 'Ciudad de Panamá, Panamá',
    'footer.efficiency': 'Eficiencia Energética',
    'footer.consulting': 'Consultoría Energética',
    'footer.advocacy': 'Defensa Energética',
    'footer.about': 'Acerca de Nosotros',
    'footer.projects': 'Proyectos',
    'footer.contact': 'Contacto',

    // Home Page
    'home.heroTitle': 'Energía Inteligente, Ahorros Reales.',
    'home.heroSubtitle': 'Claridad y control sobre tu energía.',
    'home.seeServices': 'Ver Servicios',
    'home.servicesTitle': 'Nuestros Servicios',
    'home.servicesSubtitle': 'Soluciones integrales de consultoría, eficiencia y defensa del consumidor adaptadas a tus necesidades',
    'home.service1.title': 'Consultoría Estratégica',
    'home.service1.description': 'Impulsamos decisiones estratégicas en estructuración de PPAs, Evaluación de Contratos y desarrollo de negocios sostenibles que optimizan costos y competitividad.',
    'home.service1.bullets': 'Definición de requerimientos, Solicitud de ofertas, Evaluación de ofertas, Selección del proveedor, Due Diligence de activos, Diseño de planes de negocio, Oferta de Licitaciones Públicas',
    'home.service2.title': 'Eficiencia Energética para Hogares y Negocios',
    'home.service2.description': 'Analizamos el perfil de carga de su hogar, negocio o industria para identificar soluciones de eficiencia energética.',
    'home.service2.bullets': 'Entiende tu factura eléctrica, Monitoreo del Uso de la Energía, Análisis de Consumo Energético, Identificación de Ahorros, Oportunidades con energías renovables',
    'home.service3.title': 'Calidad de Servicio',
    'home.service3.description': 'Asesoramos en reclamos por calidad del servicio eléctrico a distribuidoras de Panamá y ante el Ente Regulador (ASEP).',
    'home.service3.bullets': 'Reclamos por calidad, Asesoría regulatoria, Representación ante ASEP',
    'home.learnMore': 'Saber Más',
    'home.expertiseTitle': 'Nuestra Experiencia',
    'home.expertiseSubtitle': 'Conocimiento profundo en tecnología, mercados e implementación',
    'home.dataAiTitle': 'Ciencia de Datos e IA',
    'home.dataAiDescription': 'Análisis avanzado y aprendizaje automático para transformar tus datos energéticos en información accionable.',
    'home.panamaMarketTitle': 'Mercado y Regulación de Panamá',
    'home.panamaMarketDescription': 'Comprensión profunda de los mercados energéticos locales, regulaciones y oportunidades en Panamá.',
    'home.technologyTitle': 'Tecnología e Implementación',
    'home.technologyDescription': 'Integración e implementación perfecta de soluciones de gestión energética adaptadas a tu infraestructura.',
    'home.whyUsTitle': 'Datos, No Estimaciones',
    'home.whyUsDescription1': 'A diferencia de los consultores energéticos tradicionales que se basan en estimaciones y suposiciones, utilizamos los datos reales de tu medidor para identificar oportunidades de ahorro reales.',
    'home.ctaTitle': '¿Listo para el Control?',
    'home.ctaDescription': 'Da el primer paso hacia la claridad energética y comienza a ahorrar hoy.',
    'home.getYourQuote': 'Obtén tu Cotización',
    'home.clientsServed': 'Clientes Atendidos',
    'home.totalSavings': 'Ahorros Generados',
    'home.avgReduction': 'Reducción Promedio',
    'home.efficiencyAchieved': 'Eficiencia Lograda',
    'home.completeSupport': 'Soporte Completo',
    'home.supportDescription': 'Servicio y asistencia de principio a fin',
    'home.scrollIndicator': 'Desliza para ver más',

    // Quote Results Page
    'quote.results.title': 'Tu Análisis Personalizado',
    'quote.results.hello': 'Hola',
    'quote.results.company': 'Empresa',
    'quote.results.property': 'pies cuadrados • Tipo',
    'quote.results.analysisComplete': 'Análisis Completado',
    'quote.results.preliminaryNotice': 'Análisis Preliminar',
    'quote.results.preliminaryText': 'Estos resultados son estimaciones basadas en información general. Para un análisis completo y personalizado, necesitaremos realizar una evaluación detallada en tu propiedad.',
    'quote.results.billAnalysis': 'Análisis de tu Factura',
    'quote.results.currentConsumption': 'Consumo Actual',
    'quote.results.monthlyAverage': 'Promedio Mensual',
    'quote.results.annualTotal': 'Total Anual',
    'quote.results.peakDemand': 'Demanda Pico',
    'quote.results.avgDailyConsumption': 'Consumo Diario Promedio',
    'quote.results.efficiencyRating': 'Calificación de Eficiencia',
    'quote.results.belowAverage': 'Por debajo del promedio',
    'quote.results.consumesMore': 'Tu propiedad consume más energía de la necesaria',
    'quote.results.wasteFactors': 'Principales Factores de Desperdicio',
    'quote.results.wasteFactor1': 'Consumo en horas pico',
    'quote.results.wasteFactor2': 'Equipos antiguos',
    'quote.results.wasteFactor3': 'Falta de gestión inteligente',
    'quote.results.wasteFactor4': 'Iluminación no optimizada',
    'quote.results.peakHoursAnalysis': 'Análisis de Horas Pico',
    'quote.results.morning': 'Mañana',
    'quote.results.afternoon': 'Tarde',
    'quote.results.evening': 'Noche',
    'quote.results.opportunity': 'Oportunidad',
    'quote.results.opportunityText': 'Optimizar el uso durante estas horas puede reducir significativamente tus costos',
    'quote.results.savingsPotential': 'Potencial de Ahorro',
    'quote.results.preliminaryProjections': 'Proyecciones basadas en análisis preliminar',
    'quote.results.monthlySavings': 'Ahorro Mensual',
    'quote.results.reduction': 'de reducción',
    'quote.results.annualSavings': 'Ahorro Anual',
    'quote.results.basedOnOptimization': 'Basado en optimización completa',
    'quote.results.fiveYearProjection': 'Proyección a 5 Años',
    'quote.results.totalEstimatedSavings': 'Ahorros totales estimados',
    'quote.results.quoteSummary': 'Resumen de la Cotización',
    'quote.results.serviceDetails': 'Detalles del Servicio',
    'quote.results.selectedService': 'Servicio Seleccionado',
    'quote.results.energyEfficiency': 'Eficiencia Energética',
    'quote.results.propertyType': 'Tipo de Propiedad',
    'quote.results.area': 'Área',
    'quote.results.sqFeet': 'pies cuadrados',
    'quote.results.measurementDevice': 'Dispositivo de Medición',
    'quote.results.purchase': 'Compra',
    'quote.results.rental': 'Alquiler',
    'quote.results.connectivity': 'Conectividad',
    'quote.results.estimatedInvestment': 'Inversión Estimada',
    'quote.results.analysisOptimization': 'Análisis y Optimización',
    'quote.results.wifiConnectivity': 'Conectividad Wi-Fi',
    'quote.results.connectivity3g': 'Conectividad 3G',
    'quote.results.included': 'Incluido',
    'quote.results.initialTotal': 'Total Inicial',
    'quote.results.additionalMonthlyCost': 'Costo mensual adicional',
    'quote.results.roi': 'Retorno de la Inversión',
    'quote.results.roiText': 'Con ahorros estimados de ${savings}/mes, la inversión se recuperaría en aproximadamente {months} meses',
    'quote.results.whatNext': '¿Qué Sigue?',
    'quote.results.preliminaryText2': 'Este es un análisis preliminar basado en información general. Para una evaluación completa y precisa, necesitamos realizar un análisis detallado en tu propiedad.',
    'quote.results.twoOptions': 'Tienes dos opciones para continuar:',
    'quote.results.haveQuestions': '¿Tienes Preguntas?',
    'quote.results.talkToExperts': 'Habla con nuestros expertos para aclarar dudas y obtener más información sobre tu análisis.',
    'quote.results.contactExpert': 'Contactar Experto',
    'quote.results.startNow': 'Comenzar Ahora',
    'quote.results.proceedPayment': 'Procede con el pago para iniciar tu análisis detallado y optimización energética.',
    'quote.results.proceedToPayment': 'Proceder al Pago',
    'quote.results.guarantee': 'Garantía de satisfacción del 100% o te devolvemos tu dinero',
    'quote.results.loadingAnalysis': 'Cargando análisis...',
    'quote.results.estimationNote': 'Las estimaciones se basan en datos generales y pueden variar según el análisis detallado.',
    'quote.results.preliminaryAnalysisNote': 'Este es un análisis preliminar basado en información general.',
    'quote.results.projectionsNote': 'Proyección basada en análisis preliminar. Los resultados reales pueden variar.',

    // Contract Flow
    'contract.title': 'Contratar Servicio de Eficiencia Energética',
    'contract.step1': 'Información de Pago',
    'contract.step2': 'Pago Exitoso',
    'contract.step3': 'Programar Instalación',
    'contract.step4': 'Confirmación Final',
    'contract.loading': 'Cargando...',
    'contract.changeService': '← Cambiar Servicio',
    'contract.selectedService': 'Servicio seleccionado: Eficiencia Energética',
    'contract.serviceDescription': 'Ingresa los detalles de tu tarjeta para proceder con el pago del servicio.',
    'contract.summaryTitle': 'Resumen del Servicio',
    'contract.summaryFeature1': 'Análisis completo de eficiencia',
    'contract.summaryFeature2': 'Instalación de medidor inteligente',
    'contract.summaryFeature3': 'Monitoreo en tiempo real',
    'contract.summaryFeature4': 'Reportes mensuales de ahorro',
    'contract.totalToPay': 'Total a Pagar',
    'contract.includesInstallation': 'Incluye instalación y configuración',
    'contract.cardholderName': 'Nombre del titular de la tarjeta',
    'contract.cardholderPlaceholder': 'Nombre como aparece en la tarjeta',
    'contract.cardNumber': 'Número de tarjeta',
    'contract.cardNumberPlaceholder': '0000 0000 0000 0000',
    'contract.acceptCards': 'Aceptamos:',
    'contract.visaMastercard': 'Visa y Mastercard',
    'contract.expiryDate': 'Fecha de expiración',
    'contract.expiryPlaceholder': 'MM/AA',
    'contract.securityCode': 'Código de seguridad',
    'contract.securityPlaceholder': 'CVV',
    'contract.securePayment': 'Pago Seguro',
    'contract.securePaymentText': 'Tu información está protegida con cifrado SSL de 256 bits. No almacenamos datos de tarjetas.',
    'contract.completeFields': 'Por favor completa todos los campos',
    'contract.cardholderRequired': 'Nombre del titular es obligatorio',
    'contract.invalidCard': 'Número de tarjeta inválido',
    'contract.invalidExpiry': 'Fecha de expiración inválida',
    'contract.invalidCvv': 'CVV inválido',
    'contract.processingPayment': 'Procesando pago...',
    'contract.payAmount': 'Pagar $2,500',
    'contract.paymentSuccessful': '¡Pago Exitoso!',
    'contract.paymentProcessed': 'Tu pago ha sido procesado correctamente. Ahora programemos la instalación.',
    'contract.purchaseDetails': 'Detalles de la Compra',
    'contract.service': 'Servicio',
    'contract.completeEnergyEfficiency': 'Eficiencia Energética Completa',
    'contract.paymentMethod': 'Método de pago',
    'contract.cardEnding': 'Tarjeta terminada en',
    'contract.totalPaid': 'Total Pagado',
    'contract.nextStep': 'Siguiente Paso',
    'contract.nextStepText': 'Ahora necesitamos programar la instalación de tu medidor inteligente. Selecciona la fecha y hora que mejor te convenga.',
    'contract.scheduleInstallation': 'Programar Instalación',
    'contract.scheduleTitle': 'Programar Instalación',
    'contract.scheduleDescription': 'Selecciona la fecha y hora que mejor te convenga para la instalación.',
    'contract.selectDate': 'Selecciona una fecha',
    'contract.availableSlots': 'Horarios disponibles para',
    'contract.available': 'Disponible',
    'contract.appointmentSummary': 'Resumen de la Cita',
    'contract.estimatedDuration': 'Duración estimada: 2-3 horas',
    'contract.previous': 'Anterior',
    'contract.confirmingAppointment': 'Confirmando cita...',
    'contract.confirmAppointment': 'Confirmar Cita',
    'contract.allReady': '¡Todo Listo!',
    'contract.serviceContracted': 'Tu servicio ha sido contratado exitosamente. Te contactaremos pronto para confirmar los detalles.',
    'contract.yourInstallationAppointment': 'Tu Cita de Instalación',
    'contract.at': 'a las',
    'contract.nextSteps': 'Próximos Pasos',
    'contract.nextStep1': 'Recibirás un correo de confirmación con todos los detalles',
    'contract.nextStep2': 'Te llamaremos 24 horas antes para confirmar la cita',
    'contract.nextStep3': 'Un técnico certificado realizará la instalación',
    'contract.nextStep4': 'Tendrás acceso inmediato a tu dashboard de monitoreo',
    'contract.finalSummary': 'Resumen Final',
    'contract.backToHome': 'Volver al Inicio',
    'contract.myAccount': 'Mi Cuenta',
    'contract.changeAppointment': '¿Necesitas cambiar tu cita? Llámanos al (507) 6000-0000',
    'contract.days.DOM': 'DOM',
    'contract.days.LUN': 'LUN',
    'contract.days.MAR': 'MAR',
    'contract.days.MIE': 'MIÉ',
    'contract.days.JUE': 'JUE',
    'contract.days.VIE': 'VIE',
    'contract.days.SAB': 'SÁB',
    'contract.months.Ene': 'Ene',
    'contract.months.Feb': 'Feb',
    'contract.months.Mar': 'Mar',
    'contract.months.Abr': 'Abr',
    'contract.months.May': 'May',
    'contract.months.Jun': 'Jun',
    'contract.months.Jul': 'Jul',
    'contract.months.Ago': 'Ago',
    'contract.months.Sep': 'Sep',
    'contract.months.Oct': 'Oct',
    'contract.months.Nov': 'Nov',
    'contract.months.Dic': 'Dic',

    // Property Types
    'property.residential': 'Residencial',
    'property.apartment': 'Apartamento',
    'property.smallBusiness': 'Pequeña Empresa',
    'property.office': 'Oficina',
    'property.industrial': 'Industrial',

    // Inquiry Confirmation Page
    'inquiry.confirmation.title': '¡Solicitud Enviada!',
    'inquiry.confirmation.subtitle': 'Gracias por tu consulta. Nuestro equipo se pondrá en contacto contigo muy pronto.',
    'inquiry.confirmation.whatNext': '¿Qué sigue?',
    'inquiry.confirmation.within24hours': 'Dentro de 24 horas',
    'inquiry.confirmation.within24hoursText': 'Recibirás una confirmación por email y un experto revisará tu solicitud.',
    'inquiry.confirmation.initialConsultation': 'Consulta inicial',
    'inquiry.confirmation.initialConsultationText': 'Programaremos una llamada para entender mejor tus necesidades específicas.',
    'inquiry.confirmation.customProposal': 'Propuesta personalizada',
    'inquiry.confirmation.customProposalText': 'Te enviaremos una propuesta detallada adaptada a tu proyecto específico.',
    'inquiry.confirmation.needHelp': '¿Necesitas ayuda?',
    'inquiry.confirmation.phone': '+507 6000-0000',
    'inquiry.confirmation.email': 'info@teravolta.com',
    'inquiry.confirmation.schedule': 'Lunes a Viernes 8:00 AM - 6:00 PM',
    'inquiry.confirmation.backToHome': 'Volver al Inicio',
    'inquiry.confirmation.viewServices': 'Ver Servicios',
  },
};

const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguage] = useState<'en' | 'es'>('es');
  const [isHydrated, setIsHydrated] = useState(false);

  useEffect(() => {
    // Only access localStorage after component mounts (client-side only)
    const savedLanguage = localStorage.getItem('teravolta-language') as 'en' | 'es';
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'es')) {
      setLanguage(savedLanguage);
    }
    setIsHydrated(true);
  }, []);

  const handleSetLanguage = (lang: 'en' | 'es') => {
    setLanguage(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('teravolta-language', lang);
    }
  };

  const t = (key: string): string => {
    return (translations[language] as Record<string, string>)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t, isHydrated }}>
      {children}
    </LanguageContext.Provider>
  );
};

export { LanguageProvider };

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
